import Foundation
import CoreML

public final class TapClassifier {
    private let model: MLModel
    
    public init() throws {
        // Load model from bundle
        // Bundle.module is automatically generated by SPM when resources are present.
        guard let modelURL = Bundle.module.url(forResource: "tap_model", withExtension: "mlmodelc") else {
            throw NSError(domain: "TapClassifier", code: 1, userInfo: [NSLocalizedDescriptionKey: "Model not found in bundle"])
        }
        
        self.model = try MLModel(contentsOf: modelURL)
    }
    
    public init(contentsOf modelURL: URL) throws {
        self.model = try MLModel(contentsOf: modelURL)
    }
    
    public func classify(resampledData: [[Float]]) -> String? {
        // resampledData should be shape (3, 200)
        guard resampledData.count == 3, resampledData[0].count == 200 else {
            fputs("[classifier] Invalid input shape\n", stderr)
            return nil
        }
        
        do {
            let shape = [1, 3, 200] as [NSNumber]
            let array = try MLMultiArray(shape: shape, dataType: .float32)
            
            // Fill array
            for c in 0..<3 {
                for i in 0..<200 {
                    let index = [0, c, i] as [NSNumber]
                    array[index] = NSNumber(value: resampledData[c][i])
                }
            }
            
            // Create input provider
            let inputName = "input"
            let provider = try MLDictionaryFeatureProvider(dictionary: [inputName: array])
            
            // Run inference
            let output = try model.prediction(from: provider)
            
            // Get class label
            if let classLabel = output.featureValue(for: "classLabel")?.stringValue {
                return classLabel
            }
            
            return nil
        } catch {
            fputs("[classifier] Prediction error: \(error)\n", stderr)
            return nil
        }
    }
}
